dist: trusty
language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2g"
    - CODECOV_TOKEN="aa90ac0e-9edb-4b6c-9af5-898f89ce42a9"
script: ./build.sh